# ????? ????? ??? ????? ?????????? ??????
weather.city=Dnipro

# ???? API ???? ? openweathermap.org
# ???????????? ?? https://openweathermap.org/api ?? ??????? ???? ????
weather.api.key=a4282aaf877f5069f639e7237bec09aa

# ??????? ??????: metric = ???????, imperial = ?????????
weather.units=metric

# ???? ??????? (?? ????????????? 8080)
server.port=8080

